### ISSUE TITLE
Instanz lässt sich nicht starten

### ISSUE THREAD

**Issue by Plasmachef** [foxriver76/ioBroker.bring#1]
Version 0.0.10

Log:
`
2019-02-17 08:58:54.709 - info: host.raspberrypi object change system.adapter.bring.0
--
2019-02-17 08:58:54.746 - info: host.raspberrypi instance system.adapter.bring.0 started with pid 14241
2019-02-17 08:58:55.129 - error: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.bring/main.js:52
2019-02-17 08:58:55.130 - error: Caught by controller[0]: adapter.on(`stateChange`, async (id, state) => {
2019-02-17 08:58:55.130 - error: Caught by controller[0]: ^
2019-02-17 08:58:55.130 - error: Caught by controller[0]: SyntaxError: Unexpected token (
2019-02-17 08:58:55.131 - error: Caught by controller[0]: at createScript (vm.js:56:10)
2019-02-17 08:58:55.131 - error: Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
2019-02-17 08:58:55.131 - error: Caught by controller[0]: at Module._compile (module.js:549:28)
2019-02-17 08:58:55.131 - error: Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
2019-02-17 08:58:55.131 - error: Caught by controller[0]: at Module.load (module.js:494:32)
2019-02-17 08:58:55.131 - error: Caught by controller[0]: at tryModuleLoad (module.js:453:12)
2019-02-17 08:58:55.132 - error: Caught by controller[0]: at Function.Module._load (module.js:445:3)
2019-02-17 08:58:55.132 - error: Caught by controller[0]: at Module.runMain (module.js:611:10)
2019-02-17 08:58:55.132 - error: Caught by controller[0]: at run (bootstrap_node.js:387:7)
2019-02-17 08:58:55.132 - error: Caught by controller[0]: at startup (bootstrap_node.js:153:9)
2019-02-17 08:58:55.132 - error: host.raspberrypi instance system.adapter.bring.0 terminated with code 1 ()
2019-02-17 08:58:55.133 - info: host.raspberrypi Restart adapter system.adapter.bring.0 because enabled
`
Anmeldedaten sind korrekt.
Instanz auf debug bringt auch nicht mehr Infos.

Danke fürs Kümmern

**Comment by foxriver76** [comment]
Node Version < 8 nehme ich an. Falls ioBroker nach Anleitung unter Linix läuft, einfach mal wieder das System updaten 
``iobroker stop && sudo apt update && sudo apt upgrade -y && iobroker start``

Sonst bitte im Forum schauen.

**Comment by Plasmachef** [comment]
hat geholfen, danke sehr!
